site_name: Fenswood Scenario
theme: readthedocs
repo_url: https://github.com/StarlingUAS/FenswoodScenario
site_description: 'Fenswood Scenario Simulation'
docs_dir: 'docs'
copyright: Copyright &copy; 2022 University of Bristol Flight Laboratory

markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.keys:
      strict: True

plugins:
  - search
  - macros
  - enumerate-headings:
      toc_depth: 3
  - mermaid2

nav:
  - "Tutorials":
    - "1. A Brief Introduction to Linux": 'tutorials/intro_to_linux.md'
    - "2. Starling and Docker": "tutorials/starling_docker.md"
    - "3. Running the Example Fenswood Scenario": "tutorials/running.md"
    - "4. A Brief Introduction to ROS": "tutorials/intro_to_ros.md"
    - "5. Running the Example UAV Controller": "tutorials/running_controller.md"
    - "6. Inspecting and Debugging Starling with Docker and ROS": "tutorials/inspecting.md"
    - "7. Summary and Conclusion": "tutorials/summary.md"
  - "Fenswood Scenario Repository":
    - "Repository Overview": "details/repo_layout.md"
    - "Volcano Target Spawning": "details/target_spawning.md"
    - "Pick up & Drop off of Payload": "details/attach_detach.md"
    - "Gimbal Control": "details/gimbal.md"

extra_css: [ kbd.css ]
